apiVersion: apps/v1
kind: Deployment
metadata:
  name: 39-deployment
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: cithit/gartnea:latest
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: LoadBalancer 
  loadBalancerIP: 10.48.10.211                                     
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  selector:
    app: flask 
